import {DeskCore} from './core/EngineRegistry.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=(msg)=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)};
$('#year').textContent=new Date().getFullYear();
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
const fileInput=$('#fileInput'), dropZone=$('#dropZone'), fileList=$('#fileList');
$('#chooseFile').addEventListener('click',()=>fileInput.click());
fileInput.addEventListener('change',()=>showFiles(fileInput.files));
['dragenter','dragover'].forEach(e=>dropZone.addEventListener(e,x=>{x.preventDefault();dropZone.classList.add('drag')}));
['dragleave','drop'].forEach(e=>dropZone.addEventListener(e,x=>{x.preventDefault();dropZone.classList.remove('drag')}));
dropZone.addEventListener('drop',e=>showFiles(e.dataTransfer.files));
function showFiles(files){fileList.innerHTML='';[...files].forEach(f=>{const s=document.createElement('span');s.className='file-pill';s.textContent=`${f.name} • ${Math.max(1,f.size/1024).toFixed(1)} KB`;fileList.appendChild(s)});if(files.length) toast(`${files.length} file${files.length>1?'s':''} ready`)}

const dialog=$('#toolDialog'), body=$('#dialogBody'), title=$('#dialogTitle'), kicker=$('#dialogKicker');
$('#closeDialog').onclick=()=>dialog.close();
$$('[data-open-tool]').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.openTool)));
function shell(html){body.innerHTML=`<div class="dialog-content">${html}</div>`}
function openTool(type){
const meta={csv:['DATA','Excel / CSV Cleaner'],bill:['DOCUMENTS','Bill & Invoice Reader'],notes:['UNDERSTAND','Notes & PDF Explainer'],correct:['WRITING','English Corrector'],translate:['LANGUAGES','Language Workspace'],ppt:['CREATE','PPT Builder'],social:['PUBLISH','Post & Message Studio'],image:['CREATOR','Image Prep'],pdf:['DOCUMENTS','PDF Creator'],calc:['UTILITY','Calculator']}[type]||['TOOL','Desk tool'];
kicker.textContent=meta[0];title.textContent=meta[1];
if(type==='csv')shell(`<p class="muted">Clean CSV data locally: trim cells, remove blank rows and exact duplicate rows, then export the result.</p><textarea id="toolInput" placeholder="Name,Email,Course\n Ravi , ravi@example.com , EEE\n Ravi , ravi@example.com , EEE"></textarea><div class="dialog-actions"><button class="primary-btn" id="runTool">Clean CSV</button><button class="secondary-btn" id="downloadTool">Download CSV</button></div><div class="result" id="toolResult">Ready.</div>`);
else if(type==='bill')shell(`<p class="muted">Extract common bill/invoice amounts and perform deterministic arithmetic checks. Use “Items to Verify”, not accusations.</p><textarea id="toolInput" placeholder="Invoice No: INV-123\nDate: 28/09/2026\nSubtotal: 1000\nGST: 180\nTotal: 1180"></textarea><button class="primary-btn" id="runTool">Analyze document</button><div class="result" id="toolResult">Ready.</div><div class="notice">AI-generated/document-processing information may contain mistakes. Verify important details against the original. Not proof for a dispute.</div>`);
else if(type==='notes')shell(`<p class="muted">Paste notes, lecture text or copied PDF text. The Desk creates a deterministic outline, key points and action items.</p><textarea id="toolInput" placeholder="Paste your notes here..."></textarea><button class="primary-btn" id="runTool">Explain & structure</button><div class="result" id="toolResult">Ready.</div>`);
else if(type==='correct')shell(`<p class="muted">Local correction for common spacing, punctuation, capitalization and contractions.</p><textarea id="toolInput" placeholder="paste a sentence here"></textarea><button class="primary-btn" id="runTool">Correct locally</button><div class="result" id="toolResult">Ready.</div>`);
else if(type==='translate')shell(`<p class="muted">AI Adapter is currently set to <b>None</b>. No external API is called. This keeps the Desk independent of free-trial providers.</p><textarea id="toolInput" placeholder="Enter text to translate..."></textarea><div class="dialog-actions"><select id="source"><option>English</option><option>Telugu</option><option>Hindi</option></select><select id="target"><option>Telugu</option><option>Hindi</option><option>English</option><option>Tamil</option><option>Kannada</option></select><button class="primary-btn" id="runTool">Prepare translation</button></div><div class="result" id="toolResult">Provider: None — translation is not silently sent anywhere.</div>`);
else if(type==='ppt')shell(`<p class="muted">Build a real .pptx locally from a deterministic slide plan. AI can later improve wording through the adapter without changing the PPT engine.</p><input id="topic" placeholder="Presentation topic"><select id="slides"><option value="6">6 slides</option><option value="8">8 slides</option><option value="10">10 slides</option></select><button class="primary-btn" id="runTool">Build & download PPTX</button><div class="result" id="toolResult">Ready.</div>`);
else if(type==='pdf')shell(`<p class="muted">Create a real PDF locally from notes, reports or copied document text.</p><input id="pdfTitle" placeholder="PDF title" value="RacharlaGPT Desk Document"><textarea id="toolInput" placeholder="Paste content here..."></textarea><button class="primary-btn" id="runTool">Create & download PDF</button><div class="result" id="toolResult">Ready.</div>`);
else if(type==='calc')shell(`<p class="muted">Safe arithmetic parser. Example: (1000+180)*2</p><input id="calcInput" placeholder="(1000+180)*2"><button class="primary-btn" id="runTool">Calculate</button><div class="result" id="toolResult">Ready.</div>`);
else if(type==='social')shell(`<p class="muted">Create a platform-ready structured draft. No network call is required.</p><textarea id="toolInput" placeholder="Your idea or announcement..."></textarea><select id="platform"><option>LinkedIn</option><option>Instagram</option><option>WhatsApp</option><option>YouTube</option></select><button class="primary-btn" id="runTool">Create draft</button><div class="result" id="toolResult">Ready.</div>`);
else shell(`<p class="muted">Choose an image and export a resized JPEG locally.</p><input id="imageFile" type="file" accept="image/*"><label>Width <input id="imgWidth" type="number" value="1080" min="50" max="4000"></label><button class="primary-btn" id="runTool">Prepare image</button><div class="result" id="toolResult">Ready.</div>`);
if($('#runTool'))$('#runTool').onclick=()=>runTool(type);dialog.showModal();}
function runTool(type){const out=$('#toolResult');
if(type==='csv'){const r=DeskCore.excel.cleanRows(DeskCore.excel.parseCSV($('#toolInput').value.replace(/\r/g,'')));window.__csv=r.rows;out.textContent=`Rows: ${r.stats.rows}\nColumns: ${r.stats.columns}\nBlank rows removed: ${r.stats.blankRows}\nDuplicates removed: ${r.stats.duplicates}\n\n${DeskCore.excel.csvString(r.rows)}`;$('#downloadTool').onclick=()=>DeskCore.export.downloadText(DeskCore.excel.csvString(r.rows),'cleaned.csv','text/csv');return}
if(type==='bill'){const r=DeskCore.bill.analyzeBill($('#toolInput').value);out.textContent=`Subtotal: ${r.subtotal??'Not confidently found'}\nTax/GST: ${r.tax??'Not confidently found'}\nTotal: ${r.total??'Not confidently found'}\n\nArithmetic check: ${r.arithmetic===null?'not enough numeric fields':r.arithmetic?'subtotal + tax matches total':'subtotal + tax does not match total — verify the original'}\n\nItems to Verify:\n• Compare extracted amounts with the original.\n• Check tax labels/rates and line-item quantities.\n• If text was unclear, do not rely on the extraction alone.`;return}
if(type==='notes'){const r=DeskCore.document.structureText($('#toolInput').value);out.textContent=`TITLE\n${r.title}\n\nKEY POINTS\n${r.keyPoints.map((x,i)=>`${i+1}. ${x}`).join('\n')||'None detected'}\n\nACTION ITEMS\n${r.actions.map(x=>'• '+x).join('\n')||'None detected'}\n\nWORD COUNT\n${r.wordCount}`;return}
if(type==='correct'){out.textContent=DeskCore.document.correctEnglish($('#toolInput').value);return}
if(type==='translate'){DeskCore.ai.translate($('#toolInput').value,$('#source').value,$('#target').value).then(r=>out.textContent=r.ok?r.text:`Provider: ${r.provider}\n${r.reason}\n\nArchitecture: connect a provider adapter later without changing this UI.`);return}
if(type==='ppt'){const slides=DeskCore.ppt.buildSlidePlan($('#topic').value,$('#slides').value);const blob=DeskCore.ppt.createPPTX(slides);DeskCore.export.downloadBlob(blob,'racharlagpt-presentation.pptx');out.textContent=`Created ${slides.length} slides as a real PPTX file.`;return}
if(type==='pdf'){DeskCore.export.downloadBlob(DeskCore.pdf.createPDF($('#toolInput').value),'racharlagpt-desk.pdf');out.textContent='Real PDF created locally.';return}
if(type==='calc'){try{out.textContent=String(DeskCore.calculator.calculate($('#calcInput').value))}catch(e){out.textContent=e.message}return}
if(type==='social'){const t=$('#toolInput').value.trim(),p=$('#platform').value;out.textContent=`${p} DRAFT\n\n${t||'Add your idea first.'}\n\n#RacharlaGPT #${p.replace(/\s/g,'')}`;return}
if(type==='image'){const f=$('#imageFile').files[0];if(!f){out.textContent='Choose an image first.';return}const img=new Image();img.onload=()=>{const w=Math.min(4000,Math.max(50,Number($('#imgWidth').value)||1080)),h=Math.round(img.height*(w/img.width)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);c.toBlob(blob=>{DeskCore.export.downloadBlob(blob,'racharlagpt-image.jpg');out.textContent=`Prepared ${w}×${h} JPG locally.`},'image/jpeg',.92)};img.src=URL.createObjectURL(f)} }
const templates={student:'Explain this topic for a student. Include a simple summary, 5 revision points, 5 quiz questions and a short viva section.',teacher:'Turn this topic into a teacher-ready lesson outline with objectives, explanation points, examples and assessment questions.',engineering:'Explain this engineering topic with definition, principle, key formulae, practical application, assumptions and viva questions.',everyone:'Explain this in simple language, list the important points and give a practical action/checklist.'};
$$('[data-template]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.template;const input=$('#creatorInput');if(templates[t])input.value=templates[t]+'\n\nTopic: ';else{$('#creatorType').value=['linkedin','instagram','whatsapp','youtube','quiz','assignment'].includes(t)?t:'summary';input.focus()}document.querySelector('#create').scrollIntoView({behavior:'smooth'});input.focus()}));
$('#generateDraft').onclick=()=>{const t=$('#creatorInput').value.trim(),type=$('#creatorType').value;const o=$('#creatorOutput');if(!t){o.textContent='Enter a topic or rough text first.';return}const labels={summary:'SIMPLE SUMMARY',linkedin:'LINKEDIN DRAFT',instagram:'INSTAGRAM CAPTION',whatsapp:'WHATSAPP MESSAGE',quiz:'QUIZ / MCQs',assignment:'ASSIGNMENT OUTLINE'};o.textContent=`${labels[type]}\n\n${t}\n\nNEXT STEPS\n• Keep the original source available.\n• Verify names, numbers, dates and claims.\n• Adapt tone and length before publishing.`};
$('#copyOutput').onclick=async()=>{try{await navigator.clipboard.writeText($('#creatorOutput').textContent);toast('Output copied')}catch{toast('Copy is not available in this browser')}};
